### ISSUE TITLE
[Bug] Deactivated plugins issue

### ISSUE THREAD

**Issue by gergo85** [MatissJanis/oc-mail#6]
I deactivated the Rainlab User (or other plugin, which is used the mail sender). When I navigated to mja/mail/mail page, I got the following error message: No hint path defined for [rainlab.user].

**Comment by MatissJanis** [comment]
This is an interesting issue. I will try to look in to it later today.

Cheers,
Matiss

**Comment by MatissJanis** [comment]
Hey!

I just tried installing both Mja.Mail and Rainlab.user plugin on a fresh OctoberCMS installation. Then I disabled the User plugin. Once that was done I went in to the Mja.Mail plugin pages.

Everything was working well and as expected. No errors were displaying.

Could it be that this error was caused by something else and not Mja.Mail plugin?

**Comment by gergo85** [comment]
Now everything was working well for me too.
